[package]
name = "ndumpmgr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
log = "0.4.27"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
simplelog = "0.12.2"
