[package]
name = "ndumplib"
version = "0.1.0"
edition = "2024"

[dependencies]
compress-tools = "0.15.1"
hex = "0.4.3"
log = "0.4.27"
roxmltree = "0.20.0"
rusqlite = "0.37.0"
tempfile = "3.20.0"
ureq = "3.0.12"
